using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;

public partial class _Default : System.Web.UI.Page
{
    string cs = ConfigurationManager.ConnectionStrings["AdminConnectionString"].ConnectionString;
    string str;
    SqlCommand com;
    int count;
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            autogenerated();

        }
        

        if (IsPostBack)
        {
            SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["AdminConnectionString"].ConnectionString);
            conn.Open();
            string checkuser = "select count(*) from [AddRoute] where VehicleNo ='" + TextBox_Vno.Text + "'";
            SqlCommand com = new SqlCommand(checkuser, conn);
            int temp = Convert.ToInt32(com.ExecuteScalar().ToString());
            if (temp != 0)
            {
                Label_U1.Visible = true;
                Label_U1.Text = "Vehicle Route is already exists";
            }
            conn.Close();
        }
    }
    void autogenerated()
    {
        SqlConnection con = new SqlConnection(cs);
        str = "select ISNULL(MAX(RID), 0) AS Maximum from AddRoute where RID=1";
        com = new SqlCommand(str, con);
        con.Open();
        count = Convert.ToInt16(com.ExecuteScalar()) + 1;

        TextBox_RID.Text = count.ToString();
        TextBox_RID.Enabled = false;
        con.Close();
    }
    protected void Button_Add_Click(object sender, EventArgs e)
    {
        try
        {

            SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["AdminConnectionString"].ConnectionString);
            conn.Open();
            string insertQuerry = "insert into AddRoute (RID, Driver , RouteStart , RouteDestination , DepartureTime, ArrivalTime, VehicleNo) values(@rid, @vclr, @vmodel, @vtype, @cname, @locat, @vnum)";
            SqlCommand com = new SqlCommand(insertQuerry, conn);

            com.Parameters.AddWithValue("@rid", TextBox_RID.Text);
            com.Parameters.AddWithValue("@vclr", TextBox_Vd.Text);
            com.Parameters.AddWithValue("@vmodel", TextBox_Sp.Text);
            com.Parameters.AddWithValue("@vtype", TextBox_D.Text);
            com.Parameters.AddWithValue("@cname", TextBox_Dt.Text);
            com.Parameters.AddWithValue("@locat", TextBox_At.Text);
            com.Parameters.AddWithValue("@vnum", TextBox_Vno.Text);
            
            com.ExecuteNonQuery();
            {
                Label_U1.Visible = true;
                Label_U1.Text = "Route added sucessfully";
            }

            TextBox_RID.Text = "";
            TextBox_Vd.Text = "";
            TextBox_Sp.Text = "";
            TextBox_D.Text = "";
            TextBox_Dt.Text = "";
            TextBox_At.Text = "";
            TextBox_Vno.Text = "";
            autogenerated();
            conn.Close();
        }

        catch (Exception ex)
        {
            Response.Write("Error" + ex.ToString());
        }
    }

    protected void Button_C_Click(object sender, EventArgs e)
    {
        Response.Redirect("AddRoute.aspx");
    }
    protected void Button_V_Click(object sender, EventArgs e)
    {
        Response.Redirect("ViewRoute.aspx");
    }
}