using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;

public partial class AddVehicle : System.Web.UI.Page
{
    string cs = ConfigurationManager.ConnectionStrings["AdminConnectionString"].ConnectionString;
    string str;
    SqlCommand com;
    int count;
    protected void Page_Load(object sender, EventArgs e)
    {
         if (!IsPostBack)
        {
            autogenerated();

        }
        {
            TextBox_Date.Text = DateTime.Today.ToShortDateString();
            TextBox_Date.Enabled = false;
        }

        if (IsPostBack)
        {
            SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["AdminConnectionString"].ConnectionString);
            conn.Open();
            string checkuser = "select count(*) from [AddVehicle] where VehicleNo ='" + TextBox_Vid.Text + "'";
            SqlCommand com = new SqlCommand(checkuser, conn);
            int temp = Convert.ToInt32(com.ExecuteScalar().ToString());
            if (temp != 0)
            {
                Label_U1.Visible = true;
                Label_U1.Text = "Vehicle is already exists";
            }
            conn.Close();
        }
    }
    void autogenerated()
    {
        SqlConnection con = new SqlConnection(cs);
        str = "select ISNULL(MAX(CID), 0) AS Maximum from AddVehicle where CID=1";
        com = new SqlCommand(str, con);
        con.Open();
        count = Convert.ToInt16(com.ExecuteScalar()) + 1;

        TextBox_CID.Text = count.ToString();
        TextBox_CID.Enabled = false;
        con.Close();
    }
    protected void Button_Add_Click(object sender, EventArgs e)
    {
        try
        {

            SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["AdminConnectionString"].ConnectionString);
            conn.Open();
            string insertQuerry = "insert into AddVehicle (CID, VehicleNo, VehicleColor, VehicleModel, VehicleType, CustomerName, Location, Date) values(@cid, @vnum, @vclr, @vmodel, @vtype, @cname, @locat, @date)";
            SqlCommand com = new SqlCommand(insertQuerry, conn);

            com.Parameters.AddWithValue("@cid", TextBox_CID.Text);
            com.Parameters.AddWithValue("@vnum", TextBox_Vid.Text);
            com.Parameters.AddWithValue("@vclr", TextBox_Vclr.Text);
            com.Parameters.AddWithValue("@vmodel", TextBox_Vmod.Text);
            com.Parameters.AddWithValue("@vtype", DropDownList_Vtype.SelectedItem.ToString());
            com.Parameters.AddWithValue("@cname", TextBox_Cname.Text);
            com.Parameters.AddWithValue("@locat", TextBox_Add.Text);
            com.Parameters.AddWithValue("@date", TextBox_Date.Text);
            com.ExecuteNonQuery();
            {
                Label_U1.Visible = true;
                Label_U1.Text = "Vehicle added sucessfully";
            }
            
            TextBox_CID.Text = "";
            TextBox_Vid.Text = "";
            TextBox_Vclr.Text = "";
            TextBox_Vmod.Text = "";
            TextBox_Cname.Text = "";
            TextBox_Add.Text = "";
            TextBox_Date.Text = "";
            autogenerated();
            conn.Close();
        }

        catch (Exception ex)
        {
            Response.Write("Error" + ex.ToString());
        }
    }

    protected void Button_C_Click(object sender, EventArgs e)
    {
        Response.Redirect("AddVehicle.aspx");
    }
    protected void Button_V_Click(object sender, EventArgs e)
    {
        Response.Redirect("ViewVehicle.aspx");
    }
}